"""
try e exception equivale a try e catch 
"""

try:
  print(x)
except:
  print('Something went wrong')
finally:
  print('The try except is finished')